spring:
  application:
    name: pp-orchestrator
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/page_pulse}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
  cache:
    type: redis
    redis:
      time-to-live: 1h
      cache-null-values: false

confluence:
  base-url: ${CONFLUENCE_BASE_URL}
  username: ${CONFLUENCE_USERNAME}
  api-token: ${CONFLUENCE_API_TOKEN}

document:
  rules:
    stale-document:
      daysThreshold: 182
  cron-expression: "0 0/1 * * * *"
